<!-- team -->
<div class="banner-bottom py-5 my-lg-5">
	<div class="container">
		<h3 class="heading mb-5 text-capitalize text-center">Our Leaders </h3>
		<div class="row w3_testimonials_grids">

			<div class="col-md-12 col-sm-12 text-center w3layouts_team_grid">
				<h4 class="mb-2">Ennels  Jones</h4>
				<p>Founder/CEO</p>
				<hr>
			</div>
			<div class="col-md-3 col-sm-6 mt-sm-0 mt-5 text-center w3layouts_team_grid">
				<h4 class="mb-2">Williams Roxburgh</h4>
				<p>Co-Founder/Director</p>
			</div>
			<div class="col-md-3 col-sm-6 mt-md-0 mt-5 text-center w3layouts_team_grid">
				<h4 class="mb-2">Kingsley Ernest </h4>
				<p>Director</p>
			</div>
			<div class="col-md-3 col-sm-6 mt-md-0 mt-5 text-center w3layouts_team_grid">
				<h4 class="mb-2">GONZALO J. Calixta</h4>
				<p>Financial Controler.</p>
			</div>
			<div class="col-md-3 col-sm-6 mt-md-0 mt-5 text-center w3layouts_team_grid">
				<h4 class="mb-2">Antoniete Spike.</h4>
				<p>Secretary.</p>
			</div>

		</div>
	</div>
</div>
<!-- //team -->

<!-- team -->
<div class="banner-bottom py-5 my-lg-5">
	<div class="container">
		<h3 class="heading mb-5 text-capitalize text-center">Our Team </h3>
		<img src="images/team.jpg" alt=" " class="img-responsive" />
	</div>
</div>
<!-- //team -->