

<!-- services -->
<section class="services py-5 my-lg-5">
	<div class="container">
		<h3 class="heading text-center text-capitalize mb-5">What We Do</h3>
		<div class="row service_grids">
			<div class="col-lg-4 col-md-6 mb-md-0 mb-3 text-center">
				<div class="serv_grid1">
					<i class="fas mb-4 fa-mobile-alt"></i>
					<h4 class="text-uppercase">Angel Funding</h4>
					<p class="mt-4 mb-5">Consult us for your idea and project intents, funding and grants - we provide funding, capital-seeding, loan, mortgages, Technological finance validations. etc</p>
					<a href="./about-us/"> Learn more </a>
				</div>
			</div>
			<div class="col-lg-4 col-md-6 mb-md-0 mb-3 text-center">
				<div class="serv_grid1 service_grid_active">
					<i class="fas mb-4 fa-globe"></i>
					<h4 class="text-uppercase">Fin. Consulting</h4>
					<p class="mt-4 mb-5">We handle any scale of financial consultancy with blue-chip companies, working from excel-worksheets to big-data level analysis. We deliver results based on facts.</p>
					<a href="./about-us"> Learn more </a>
				</div>
			</div>
			<div class="col-lg-4 col-md-6 text-center">
				<div class="serv_grid1">
					<i class="fas mb-4 fa-desktop"></i>
					<h4 class="text-uppercase">Auditing & Report</h4>
					<p class="mt-4 mb-5">Every consult has a globally verifiable research financial track-record, we help big companies put a fine track record that is both transparent and consistently accurate.</p>
					<a href="./about-us"> Learn more </a>
				</div>
			</div>
		</div>
	</div>
</section>
<!-- //services -->


<!-- welcome bottom -->
<section class="welcome_bottom">
	<div class="layer py-5">
		<div class="container py-lg-5">
			<div class="row bottom_grids">
				<div class="col-lg-6 col-md-8">
					<h4>We are Changing the World through Research and Development</h4>
					<p class="my-4">Through research and collaborations, we invest into businesses, engineering and scientific claims, facts, global inquiry, enterprice level consults and corporate structures. We deliver our services following best acceptable standards (ISOs).</p>
					<h4 class="head text-uppercase"><i class="fas mb-4 fa-globe"></i>Global Funding</h4>
					<p class="mb-4">By offering the best results and facts, we satisfy our clients' inquisitions. Our team love what they do - passionately!</p>
					<a href="#" data-toggle="modal" data-target="#exampleModalCenter" role="button">View More <i class="fas fa-angle-right"></i></a>
				</div>
				<div class="col-lg-6 col-md-4 video text-center">
					<a href="#" class="text-uppercase" data-toggle="modal" data-target="#exampleModal"><span class="fas fa-play-circle"></span></a>
				</div>
			</div>
		</div>
	</div>
</section>
<!-- //welcome bottom -->




<!-- model video-->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
	<div class="modal-dialog" role="document">
		<div class="modal-content">
			<div class="modal-header">
				<h5 class="modal-title" id="exampleModalLabel">The Future we see!</h5>
				<button type="button" class="close" data-dismiss="modal" aria-label="Close">
					<span aria-hidden="true">&times;</span>
				</button>
			</div>
			<div class="modal-body video">
				<iframe src="https://player.vimeo.com/video/"></iframe>

			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-secondary" data-dismiss="modal">Close Window</button>
			</div>
		</div>
	</div>
</div>
<!-- //model video -->
