<ul class="navbar-nav ml-auto">
    <li class="nav-item <?= !isset($frm)?'active':'' ?>">
        <a class="nav-link" href="./">Home <span class="sr-only">(current)</span></a>
    </li>
    <li class="nav-item <?= $frm=='about-us'?'active':'' ?>">
        <a class="nav-link" href="./about-us/">About</a>
    </li>
    <li class="nav-item <?= $frm=='services'?'active':'' ?>">
        <a class="nav-link" href="./services/">Services</a>
    </li>
    <li class="nav-item <?= $frm=='the-team'?'active':'' ?>">
        <a class="nav-link" href="./the-team/">Our Team</a>
    </li>
    <li class="nav-item <?= $frm=='contact-us'?'active':'' ?>">
        <a class="nav-link" href="./contact-us/">Contact</a>
    </li>
</ul>
