
<!-- Welcome -->
<section class="welcome py-5 my-lg-5">
	<div class="container">
		<div class="row welcome_grids">
		  	<div class="col-lg-7 mb-lg-0">
			  <h3 class="mb-3 text-capitalize">Welcome to CR Associate & Finance LLC.</h3>
			  <p class="mb-5 mt-0">Bridging this financing gap is what CR Associate & Finance was established to achieve twelve ago, and our mission has remained the same ever since. CR Associate & Finance is an independent, majority private sector owned, multi-lateral global financial institution providing project structuring expertise and risk capital to address world’s pressing infrastructure, capacity and economic development needs.</p>
			</div>
			<div class="col-lg-5 welcome_right">
				<img src="images/slide1.jpg" class="img-fluid">
			</div>
		</div>
        
		<div class="row">
		  	<div class="col-lg-7 mb-lg-0 mb-5">
			  <p class="mb-5 mt-0">The CR Associate & Financial Advisory Department provides financial and technical advice to public and private sector clients across Africa, in the areas of infrastructure project development, transaction management, policy formulation and implementation, project financing, mergers, acquisitions, fund management and corporate restructurings.</p>
			  <p class="mb-5 mt-4">The Corporation also partners with a broad range of international and local institutions focused on Europe, Asia and America, with a view to delivering high quality advisory input to sponsors, governments and corporate groups that are seeking to develop significant infrastructure projects Globally.
</p>
			  <p class="mb-5 mt-4">&nbsp;</p>
			</div>
			<div class="col-lg-5"></div>
		</div>
        
	</div>
</section>
<!-- //Welcome -->


<!-- help -->
<section class="help">
	<div class="layer py-5">
		<div class="container py-lg-5">
		<h3 class="heading text-center text-capitalize mb-5">We help you in </h3>
			<div class="row help_grids">
				<div class="col-sm-4">
					<div class="row">
						<div class="col-lg-3 mb-lg-0 mb-4 icon">
							<i class="fas fa-briefcase"></i>
						</div>
						<div class="col-lg-9">
							<h4 class="text-uppercase mb-3">Business</h4>
							<a href="./services/">Read More <i class="fas fa-angle-right"></i></a>
						</div>
					</div>
				</div>
				<div class="col-sm-4 mt-sm-0 mt-4">
					<div class="row">
						<div class="col-lg-3 mb-lg-0 mb-4 icon">
							<i class="fas fa-signal"></i>
						</div>
						<div class="col-lg-9">
							<h4 class="text-uppercase mb-3">Strategy</h4>
							<a href="./services/">Read More <i class="fas fa-angle-right"></i></a>
						</div>
					</div>
				</div>
				<div class="col-sm-4 mt-sm-0 mt-4">
					<div class="row">
						<div class="col-lg-3 mb-lg-0 mb-4 icon">
							<i class="fab fa-connectdevelop"></i>
						</div>
						<div class="col-lg-9">
							<h4 class="text-uppercase mb-3">Technology</h4>
							<a href="./services/">Read More <i class="fas fa-angle-right"></i></a>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>
<!-- //help -->

